In [1]:
import pandas as pd
from dbfread import DBF

In [ ]:
tabla_dbf_primaria = DBF('../../data/raw/censo_educativo/Lineal_3AP_1.dbf', encoding='cp1252')
tabla_dbf_secundaria = DBF('../../data/raw/censo_educativo/Lineal_3AS_1.dbf', encoding='cp1252')
df_listado_ieee = pd.read_html('../../data/raw/mapa_servicio_educativo/listado_iiee.xls')
df_matricula_suma = pd.read_csv('../../data/raw/censo_educativo/matricula_suma.csv')

In [3]:
df_listado_ieee = pd.read_html('../../data/raw/mapa_servicio_educativo/listado_iiee.xls')

AttributeError: 'list' object has no attribute 'shape'

In [3]:
df_primaria = pd.DataFrame(iter(tabla_dbf_primaria))
df_secundaria = pd.DataFrame(iter(tabla_dbf_secundaria))

In [4]:
df_primaria.head()

,COD_MOD,ANEXO,CODLOCAL,NROCED,CEN_EDU,DISTRITO,LOCALIDAD,P104A,P105A,P105A_S_1,...,P136B_S_1,P136B_S_2,P136B_S_3,P136B_S_4,P136B_S_4O,NIV_MOD,GES_DEP,AREA_CENSO,CODGEO,CODOOII
0,1720556,0,852373,3AP,SIR ALEXANDER FLEMING,CERCADO,,NO,,,...,X,X,,,,B0,B4,1,040101,040001
1,0313890,0,073181,3AP,40513 SAN MIGUEL ARCANGEL,ALCA,ANEXO DE CAHUANA,NO,,,...,X,X,X,,,B0,A1,2,040802,040009
2,1495092,0,605028,3AP,33421,PILLCO MARCA,CAYHUAYNA,NO,,,...,,,,,,B0,A1,1,100111,100001
3,1579861,0,651751,3AP,SANTANDER DE PUENTE PIEDRA,PUENTE PIEDRA,SANTA PAULA,NO,,,...,,,,,,B0,B4,1,150125,150105
4,1529767,0,553166,3AP,COLEGIO SUPERIOR DE CIENCIAS NEWTON VIANNEY,YURA,,NO,,,...,,X,,,,B0,B4,1,040128,040001

In [5]:
df_secundaria.head()

,COD_MOD,ANEXO,CODLOCAL,NROCED,CEN_EDU,DISTRITO,LOCALIDAD,MSE_EBR,MSE_ST,P5_FORMA,...,P139B_S_1,P139B_S_2,P139B_S_3,P139B_S_4,P139B_S_4O,NIV_MOD,GES_DEP,AREA_CENSO,CODGEO,CODOOII
0,1574086,0,646986,3AS,MICAELA BASTIDAS,ANCO,SANTA CRUZ DE CCONOCC,1,,1,...,,X,,,,F0,A1,2,090502,090005
1,0372953,0,249312,3AS,INDOAMERICANO,SAN JUAN DE JARPA,JARPA,1,,1,...,X,,,,,F0,A1,2,120907,120002
2,1777267,0,269932,3AS,82018,COCHORCO,VAQUERIA,1,,1,...,X,,,,,F0,A1,2,130903,130010
3,0619189,0,236319,3AS,JOSE ANTONIO ENCINAS FRANCO,JANJAILLO,JANJAILLO,1,,1,...,X,,,,,F0,A1,2,120411,120005
4,0638932,0,355864,3AS,20395 NUESTRA SEÑORA DE FATIMA,CHANCAY,QUEPEPAMPA,2,,2,...,X,,,,,F0,A1,1,150605,150203

In [8]:
#combinar df primaria y secundaria y solo dejar las columnas COD_MOD, CODLOCAL, CODGEO, CEN_EDU, DISTRITO, LOCALIDAD
df_primaria_secundaria = pd.concat([df_primaria, df_secundaria], ignore_index=True)
df_primaria_secundaria = df_primaria_secundaria[["COD_MOD", "CODLOCAL", "CODGEO", "CEN_EDU", "DISTRITO", "LOCALIDAD"]]
df_primaria_secundaria.head()
df_primaria_secundaria.to_csv('../../data/cleaned/primaria_secundaria.csv', index=False)

In [ ]:

df_primaria_secundaria.shape

(52626, 6)

In [15]:
df_listado_ieee[0].head()

,Código Institución,Código Modular,Anexo,Nombre de SS.EE.,Ubigeo,Departamento,Provincia,Distrito,Código DRE/UGEL,DRE / UGEL,Centro Poblado,Código Centro Poblado,Código Local,Dirección,Nivel / Modalidad,Gestion / Dependencia,Latitud,Longitud,Altitud,Fuente de coordenadas
0,NaN,3994635,0,PEQUEÑOS ANGELES,40101,AREQUIPA,AREQUIPA,AREQUIPA,40001,AREQUIPA NORTE,7 DE JUNIO,557772,105451.0,CALLE FRANCISCO BOLOGNESI S/N,Inicial No Escolarizado,Pública - Sector Educación,-16.440842,-71.577918,2236,MED_REG (LOCAL)
1,22281046.0,1752989,0,VIGOUSKY SCHOOL,40101,AREQUIPA,AREQUIPA,AREQUIPA,40001,AREQUIPA NORTE,ABRAHAM MANRIQUE,570304,826398.0,ABRAHAM MANRIQUE MZ A LOTE 4,Inicial - Jardín,Privada - Particular,-16.420220,-71.540420,2303,UBICACION_WEB (LOCAL)
2,26198232.0,1237908,0,ALAS PERUANAS,40101,AREQUIPA,AREQUIPA,AREQUIPA,40001,AREQUIPA NORTE,APROVIORD,574202,57044.0,APROVIORD MZ B LOTE 6,Inicial - Jardín,Privada - Particular,-16.411600,-71.524800,2351,UGEL_GPS (LOCAL)
3,26198232.0,1030410,0,ALAS PERUANAS,40101,AREQUIPA,AREQUIPA,AREQUIPA,40001,AREQUIPA NORTE,APROVIORD,574202,57044.0,APROVIORD MZ B LOTE 6,Secundaria,Privada - Particular,-16.411600,-71.524800,2351,UGEL_GPS (LOCAL)
4,26198232.0,1030402,0,ALAS PERUANAS,40101,AREQUIPA,AREQUIPA,AREQUIPA,40001,AREQUIPA NORTE,APROVIORD,574202,57044.0,APROVIORD MZ B LOTE 6,Primaria,Privada - Particular,-16.411600,-71.524800,2351,UGEL_GPS (LOCAL)

In [20]:
#ver que valores de COD_MOD hay en el df_primaria_secundaria y que también estén en df_listado_ieee en la columna 'Código Modular'
coincidencias = df_primaria_secundaria['COD_MOD'].isin(df_listado_ieee[0]['Código Modular']).sum()
coincidencias

np.int64(0)

In [23]:
df_primaria_secundaria[df_primaria_secundaria['COD_MOD'] == "3994635"]

Empty DataFrame
Columns: [COD_MOD, CODLOCAL, CODGEO, CEN_EDU, DISTRITO, LOCALIDAD]
Index: []