In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('data_colegios.csv', sep=";")
df_aqp= pd.read_csv("./arequipa_colegios.csv")

/tmp/ipykernel_6123/2318886359.py:1: DtypeWarning: Columns (0: TIPSSEXO, 1: COD_TUR) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data_colegios.csv', sep=";")

In [7]:
df_aqp.head()

,Latitud,Longitud,Nombre_del_colegio,Alumnos_matriculados,Brecha_total_estimada_en_soles,Ratio_de_demolicion,Nombre_de_la_IE,Matriculados,Total_de_mesas_unipersonales,Total_de_mesas_unipersonales_en_mal_estado,...,Total_de_sillas,Total_de_sillas_en_mal_estado,Total_de_pizarras,Total_de_pizarras_en_mal_estado,Total_de_carpetas_unipersonales,Total_de_carpetas_bipersonales,Condicion_del_servicio_de_agua,Condicion_del_servicio_de_alcantarillado,Condicion_del_servicio_de_energia_electrica,Acceso_a_internet
0,-16.33,-71.55,JOSE CARUANA,172.0,"1.958.234,8","5,9%",167,8,0.0,0.0,...,35.0,0.0,3.0,0.0,0.0,0.0,Inadecuado,Inadecuado,Adecuado,Sí
1,-16.39,-71.53,40001 LUIS H. BOURONCLE,445.0,"5.186.627,6","0,0%",190,30,0.0,0.0,...,37.0,0.0,3.0,0.0,0.0,0.0,Adecuado,Adecuado,Adecuado,Sí
2,-16.41,-71.54,40002 AL AIRE LIBRE/40002 AL AIRE LIBRE,321.0,"897.932,0","0,0%",24136,9,0.0,0.0,...,20.0,0.0,2.0,0.0,0.0,0.0,Inadecuado,Inadecuado,Adecuado,Sí
3,-16.41,-71.52,40007 GILBERTO OCHOA GALDOS/40007 GILBERTO OCH...,170.0,"3.002.442,6","1,4%",24138,49,4.0,0.0,...,49.0,0.0,6.0,0.0,0.0,33.0,Adecuado,Adecuado,Adecuado,No
4,-16.42,-71.55,SANTO DOMINGO DE GUZMAN/SANTO DOMINGO DE GUZMA...,55.0,"1.237.986,4","0,0%",24092,44,0.0,0.0,...,65.0,0.0,5.0,0.0,0.0,65.0,Adecuado,Adecuado,Adecuado,No

In [11]:
df_aqp.columns
COLUMNS = ['Nombre_del_colegio', 'Condicion_del_servicio_de_energia_electrica', 'Acceso_a_internet']
df_internet = df_aqp[COLUMNS]
df_internet.head()

,Nombre_del_colegio,Condicion_del_servicio_de_energia_electrica,Acceso_a_internet
0,JOSE CARUANA,Adecuado,Sí
1,40001 LUIS H. BOURONCLE,Adecuado,Sí
2,40002 AL AIRE LIBRE/40002 AL AIRE LIBRE,Adecuado,Sí
3,40007 GILBERTO OCHOA GALDOS/40007 GILBERTO OCH...,Adecuado,No
4,SANTO DOMINGO DE GUZMAN/SANTO DOMINGO DE GUZMA...,Adecuado,No